config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :project_categories

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :funds do
    member do
      get :confirm_mail
    end
  end
  resources :wishlists
  resources :user_promises
  resources :categories
  resources :promises
  resources :project_users
  resources :projects
  resources :users
  resources :searches


  root to: 'application#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :funds,:dependent => :destroy
	has_many :wishlists ,:dependent => :destroy
	has_many :promises ,:dependent => :destroy
	has_many :project_categories ,:dependent => :destroy
	has_many :categories, :through => :project_categories
	has_attached_file :image ,  styles: { medium: "200x200>", big: "500x500" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	validates :title, presence: true
	validates :info, presence: true
	validates :goal, numericality: {greater_than_or_equal_to: 0}
	validates :daystogo, numericality: {greater_than_or_equal_to: 0}
	def self.search(search)
		if search
			where(["title LIKE ?", "%#{search}%"])
		else
			all
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:create, :index]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.search(params[:search])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project.user.name
    @promises = @project.promises
    @categories = @project.categories
    @funds = @project.funds
    @total = 0
    @funds.each do |fund|
      if fund.fund_confirmed== true
      @total = @total + fund.cost
      end
    end
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to new_project_category_path(pc_id: @project.id) }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit( :title, :info, :goal, :daystogo, :release, :user_id, :image)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">
</head>
<body>



<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>

<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>


<div class="container">
  <div class="jumbotron">
    <h1>New Project</h1>
    <%= form_for @project, html: { multipart: true },method: 'PATCH' do |xx| %>
      <div> <%= xx.file_field :image  %></div>
      <label for="cost1">Project title</label>
      <div> <%= xx.text_field :title  %></div>
      <label for="cost1">Description</label>
      <div> <%= xx.text_field :info%></div>
      <label for="cost1">Goal</label>
      <div> <%= xx.text_field :goal  %></div>
      <label for="cost1">Days to go</label>
      <div> <%= xx.text_field :daystogo  %></div>

      <a class="btn btn-primary m-1"  role="button"><%= xx.submit  %></a>





      </div>




    <% end %>

    </div>
















  <div class="actions">
   
  </div>
</div>




<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">
</head>
<body>



<!-- Navigation -->
<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>



<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>



<h1>Projects</h1>
     <% @projects.each do |project| %>
  <div class="container">
    <div class="jumbotron">
  <tr>
    <%= image_tag project.image.url(:medium) %>
	<li><%= project.title %></li>

    <td><%= link_to 'Show', project %></td>
        <% if  project.user == current_user %>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <%end%>
          </tr>
    </div>
    <% end %>







<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">
</head>
<body>



<!-- Navigation -->
<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>


<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>


  <div class="container">
    <div class="jumbotron">
      <h1>New Project</h1>
<%= form_for @project, html: { multipart: true },method: 'POST' do |xx| %>
        <div> <%= xx.file_field :image  %></div>
        <label for="cost1">Project title</label>
       <div> <%= xx.text_field :title  %></div>
       <label for="cost1">Description</label>
        <div> <%= xx.text_field :info%></div>
       <label for="cost1">Goal</label>
        <div> <%= xx.text_field :goal  %></div>
       <label for="cost1">Days to go</label>
        <div> <%= xx.text_field :daystogo  %></div>

       <a class="btn btn-primary m-1"  role="button"><%= xx.submit  %></a>





</div>




<% end %>

      </div>

app/views/projects/show.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">
</head>
<body>



<!-- Navigation -->
<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div class="container-fluid padding">

<div class="row padding">
 <div class="col-md-4">
  <div class="card">
   <%= image_tag @project.image.url(:medium)%>
   <div class="card-body">
    <h4 class="card-title">  <%= markdown ('#'+@project.title) %> </h4>
     <p class="card-text">by: <%= @project.user.name %> </p>
    <p class="card-text"> <%= markdown(@project.info )%> </p>
     <% if  @project.user == current_user %>
     <td><%= link_to 'Edit', edit_project_path(@project) %></td>
     <td><%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
     <% end %>
     <div></div>
     <% @categories.each do |category| %>
       <td> <%="Category " +category.name %> </td>
       <td><%= link_to 'Show', category %></td>
       <div></div>
     <% end %>


   </div>
  </div>
 </div>
 <div class="col-md-4">
  <div class="card">
   <div class="progress">
     <div class="progress-bar" role="progressbar" style="width:     <%= 100*(@total)/(@project.goal) %>%
     " aria-valuenow="87" aria-valuemin="0" aria-valuemax="100"><%= 100*(@total)/(@project.goal) %>%</div>
     </div>
    <div class="card-body">
     <h4 class="card-title"> GOAL: <%= @project.goal %> </h4>
     <p class="card-text"> Days to go: <%= @project.daystogo %> </p>
     <form>
      <div class="form-group">
      </div>
     </form>
      <%= link_to 'Fund it', new_fund_path(u_id: @current_user.id , f_id: @project.id  ) %>
    </div>
      <div></div>

    <%= link_to 'Add to wishlist', new_wishlist_path(uu_id: @current_user.id , w_id: @project.id  ) %>
  </div>
  </div>
 </div>
</div>
</div>
<div class="container-fluid padding">
<div class="row texct-center padding">
 <div class="col-xs-12">
  
 </div>
</div>
<hr class="my-4">
</div>


<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp;
</div>


<% @promises.each do |promise| %>



  <tbody>

  <tr>
    <div class="container-fluid padding">

      <div class="row padding">
        <div class="col-md-2">
          <div class="card">

            <div class="card-body">
              <%= image_tag promise.image.url(:medium)%>
              <h4 class="card-title">  <%= promise.title %> </h4>
              <p class="card-text"> <%= promise.info %> </p>
              <p class="card-text"> Price: <%= promise.price %> </p>
              <%= link_to 'BUY', new_fund_path(u_id: @current_user.id , f_id: @project.id , p_cost: promise.price ) %>
              <% if  promise.project_id == @project.id && @project.user == current_user %>

                <td><%= link_to 'Edit', edit_promise_path(promise) %></td>
                <td><%= link_to 'Destroy',promise, method: :delete, data: { confirm: 'Are you sure?' } %></td>

            <%end%>

            </div>
          </div>
        </div>
      </div>
    </div>
    </div>




  </tr>

  </tbody>



  <div></div>
<% end %>



<div></div>
<% if  @project.user == current_user %>

  <%= link_to 'New Promise', new_promise_path(p_id: @project.id) %>
<%end%>
<div></div>
<div></div>