config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :project_categories

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :funds do
    member do
      get :confirm_mail
    end
  end
  resources :wishlists
  resources :user_promises
  resources :categories
  resources :promises
  resources :project_users
  resources :projects
  resources :users
  resources :searches


  root to: 'application#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project_category.rb
class ProjectCategory < ApplicationRecord
  belongs_to :project
  belongs_to :category
end

app/controllers/project_categories_controller.rb
class ProjectCategoriesController < ApplicationController
  before_action :set_project_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /project_categories
  # GET /project_categories.json
  def index
    @project_categories = ProjectCategory.all
  end

  # GET /project_categories/1
  # GET /project_categories/1.json
  def show
  end

  # GET /project_categories/new
  def new
    @project_category = ProjectCategory.new
    @idd = params[:pc_id]
  end

  # GET /project_categories/1/edit
  def edit
  end

  # POST /project_categories
  # POST /project_categories.json
  def create
    @project_category = ProjectCategory.new(project_category_params)

    respond_to do |format|
      if @project_category.save
        format.html { redirect_to "/projects/"+@project_category.project_id.to_s, notice: 'Project  was successfully created.' }
        format.json { render :show, status: :created, location: @project_category }
      else
        format.html { render :new }
        format.json { render json: @project_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_categories/1
  # PATCH/PUT /project_categories/1.json
  def update
    respond_to do |format|
      if @project_category.update(project_category_params)
        format.html { redirect_to @project_category, notice: 'Project category was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_category }
      else
        format.html { render :edit }
        format.json { render json: @project_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_categories/1
  # DELETE /project_categories/1.json
  def destroy
    @project_category.destroy
    respond_to do |format|
      format.html { redirect_to project_categories_url, notice: 'Project category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_category
      @project_category = ProjectCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_category_params
      params.require(:project_category).permit( :project_id, :category_id)
    end
end

app/helpers/project_categories_helper.rb
module ProjectCategoriesHelper
end

app/views/project_categories/_form.html.erb
<%= form_with(model: project_category, local: true) do |form| %>
  <% if project_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_category.errors.count, "error") %> prohibited this project_category from being saved:</h2>

      <ul>
      <% project_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project_categories/edit.html.erb
<h1>Editing Project Category</h1>

<%= render 'form', project_category: @project_category %>

<%= link_to 'Show', @project_category %> |
<%= link_to 'Back', project_categories_path %>

app/views/project_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_categories.each do |project_category| %>
      <tr>
        <td><%= link_to 'Show', project_category %></td>
        <td><%= link_to 'Edit', edit_project_category_path(project_category) %></td>
        <td><%= link_to 'Destroy', project_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project Category', new_project_category_path %>

app/views/project_categories/new.html.erb
<p id="notice"><%= notice %></p>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

</head>
<body>



<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>


<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>

<div class="container">
  <div class="jumbotron">
    <h1>Select Category</h1>
    <%=form_for @project_category, method: 'POST' do |xx| %>


      <p> <%= xx.hidden_field :project_id, :value => @idd%></p>
      <%= xx.collection_select(:category_id ,Category.all, :id,:name, include_blank: true) %>

      <a class="btn btn-primary m-1"  role="button"><%= xx.submit "Create Proyect" %></a>

      </div>
    <%end%>



  </div>

app/views/project_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_category_path(@project_category) %> |
<%= link_to 'Back', project_categories_path %>