config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :project_categories

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :funds do
    member do
      get :confirm_mail
    end
  end
  resources :wishlists
  resources :user_promises
  resources :categories
  resources :promises
  resources :project_users
  resources :projects
  resources :users
  resources :searches


  root to: 'application#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :project_categories ,:dependent => :destroy
	has_many :projects, :through => :project_categories
	validates :name , presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @projects = @category.projects
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit( :name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">
</head>
<body>



<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>







</body>
</html>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>


  <h2>Categories</h2>
  <% @categories.each do |category| %>
  <div class="container">


          <div class="list-group">
            <div class="list-group-item list-group-item-action" <tr>  <%=link_to category.name, category_path(category) %> </tr>


            </div>
          </div>
        </div>
  <% end %>











  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">
</head>
<body>



<!-- Navigation -->
<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>


<h1>New Category</h1>

<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>


  <div class="container">
    <div class="jumbotron">
      <h1>New Category</h1>
<%= form_for @category, method: 'POST' do |xx| %>
       <label for="cost1">Category Name</label>
       <div> <%= xx.text_field :name  %></div>

       <a class="btn btn-primary m-1"  role="button"><%= xx.submit  %></a>


</div>
<% end %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">
</head>
<body>



<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>
<p id="notice"><%= notice %></p>


<% @projects.each do |project| %>
  <div class="container">
    <div class="jumbotron">
      <tr>
    <%= image_tag project.image.url(:medium) %>
  <td> <%= project.title %> </td>
  <td><%= link_to 'Show', project %></td>
      </tr>
  <div></div>
    </div>
  </div>
<% end %>