config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :project_categories

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :funds do
    member do
      get :confirm_mail
    end
  end
  resources :wishlists
  resources :user_promises
  resources :categories
  resources :promises
  resources :project_users
  resources :projects
  resources :users
  resources :searches


  root to: 'application#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fund.rb
class Fund < ApplicationRecord
	belongs_to :user
	belongs_to :project
	before_create :confirmation_token

	#validates :stagemail, presence: true
	#validates :stageaprove, presence: true
	#validates :stagereceive, presence: true
	def mail_activate
		self.fund_confirmed = true
		self.confirm_token = nil
		save!(validate => false )
	end
	private
	def confirmation_token
		if self.confirm_token.blank?
			self.confirm_token = SecureRandom.urlsafe_base64.to_s
		end
	end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :set_fund, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
  end

  # GET /funds/new
  def new
    @fund = Fund.new
    @uid = params[:u_id]
    @pid = params[:f_id]
    @pcost = params[:p_cost]

  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  # POST /funds.json
  def create
    @uid = params[:u_id]
    @fund = Fund.new(fund_params)

    respond_to do |format|

      if @fund.save
        FundMailer.fund_confirmation(@fund, current_user ).deliver

        format.html { redirect_to "/projects/"+@fund.project_id.to_s, notice: 'Confirm Fund In Email.' }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm_mail
    @pid = params[:f_id]
    fund = Fund.find_by_confirm_token(params[:id])
    if fund
      fund.mail_activate
      redirect_to '/',notice: 'Fund Succesfully Confirmed.'


    else
      redirect_to '/users'
    end
    end

  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit( :user_id, :project_id, :cost)
    end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.erb
<%= form_with(model: fund, local: true) do |form| %>
  <% if fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
      <% fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/funds/edit.html.erb
<h1>Editing Fund</h1>

<%= render 'form', fund: @fund %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

app/views/funds/index.html.erb
<p id="notice"><%= notice %></p>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="style.css" rel="stylesheet">
</head>
<body>



<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>

<h1>Funds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<form>
  <div class="form-group">
    <label for="cost1">How much do you want to fund?</label>
    <input type="cost" class="form-control" id="cost1" aria-describedby="emailHelp" placeholder="Enter amount">
  </div>
</form>
<a href="/funds" class="btn btn-primary m-1"  role="button">Fund it</a>
    <% @funds.each do |fund| %>
      <tr>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/funds/new.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Complete Bootstrap 4 Website Layout</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <link href="application.css" rel="stylesheets">
</head>
<body>



<!-- Navigation -->
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src="/assets/Fundtastic-a7da83e586ce1ac15efe236b73a85363344eb9134e595c194dd0a526b6c89567.jpg" width="150"></a>


    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/categories">Explore</a>


        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>


        <%=link_to"Search it", new_search_path%>

      </ul>
      <% if current_user.try(:admin?) %>
        <a class="btn btn-info" style="color:#ffffff" href="/admin">Administration</a>
      <% end %>

      <div>

        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

      </div>


      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="btn btn-info" style="color:#ffffff" href="/projects">Get Funded</a>

        </li>
        <div>

          &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

        </div>



        <% if user_signed_in? %>
          <li class="nav-item active">
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" style="color:#ffffff" type="button" data-toggle="dropdown"> <%= current_user.name %>
                <span class="caret"></span></button>
              <ul class="dropdown-menu">

                <li><%= link_to "Profile", user_path(current_user), :style=> 'color:#ffffff;'%></li>
                <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :style=> 'color:#ffffff;'%></li>

              </ul>
            </div>






        <%else%>
          <a class="btn btn-info" style="color:#ffffff" href="/users/sign_in">Log in</a>


        <%end%>
        </li>

      </ul>

    </div>


  </div>
</nav>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>
<div>

  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

</div>

<% if @pcost == nil %>
<div class="container">
  <div class="jumbotron">
    <%=form_for @fund, method: 'POST' do |xx| %>
      <label for="cost1">Amount to fund</label>
      <div> <%= xx.text_field :cost  %></div>
      <p> <%= xx.hidden_field :user_id, :value => @uid%></p>
      <p> <%= xx.hidden_field :project_id, :value => @pid%></p>
      <a class="btn btn-primary m-1"  role="button"><%= xx.submit  %></a>
      </div>
      <%end%>
<% else %>
      <div class="container">
        <div class="jumbotron">
          <%=form_for @fund, method: 'POST' do |xx| %>
            <label for="cost1">Are you sure you want to  buy a <%= @pcost %> $promise? </label>

            <div> <%= xx.hidden_field :cost, :value => @pcost  %></div>
            <p> <%= xx.hidden_field :user_id, :value => @uid%></p>
            <p> <%= xx.hidden_field :project_id, :value => @pid%></p>
            <a class="btn btn-primary m-1"  role="button"><%= xx.submit "Yes" %></a>
            </div>
    <%end%>
    <% end %>

app/views/funds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fund_path(@fund) %> |
<%= link_to 'Back', funds_path %>